[package]
name = "ppml-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "~1.0.1", features = ["boolean", "shortint", "integer", "gpu"] }
clap = { version = "4", features = ["derive"] }